### ISSUE TITLE
How to explicitly define float point registers as 'float'.

### ISSUE THREAD

**Issue by nihilus** [yegord/snowman#58] opened 2015-09-19 16:16 UTC
As now they get defined as int32_t for me, however I guess there is a way to create explicit statements for getting the correct type? Right?

**Comment by yegord** [comment] 2015-09-19 20:18
Right.
Types are inferred by TypeAnalyzer from the operations performed on the objects.
Currently IR does not have any floating-point operations; this should be fixed eventually, see also https://github.com/yegord/snowman/issues/28.

Topic-wise, I am not sure that it is a good idea to infer the type of a value based on its memory location.

**Comment by nihilus** [comment] 2015-09-19 20:28
There are in the MIPS ISA special assembly opcodes for converting data types of float point registers.

**Comment by yegord** [comment] 2015-09-19 20:34
Yep. But there are no floating point operations in IR. You are welcome to add them. :)
Once you have added them and defined the semantics of floating-point instructions, you will get floating-point types.

**Comment by yegord** [comment] 2015-10-05 22:41
Duplicate of https://github.com/yegord/snowman/issues/28

**Closed by yegord** 2015-10-05 22:41 UTC
Labels: duplicate

**Comment by nihilus** [comment] 2015-10-05 22:46
Id say #28 is a sub-issue of this one. Since SSE2 is not about float pointing arithmetics but SIMD and is very x86 specific. Better close #28 and leave this more generic issue open.

**Comment by yegord** [comment] 2015-10-05 23:11
#28 was submitted earlier.
