### ISSUE TITLE
Weird return value for a MIPS/Allegrex function

### ISSUE THREAD

**Issue by hlide** [yegord/snowman#57] opened 2015-09-19 11:26 UTC
Decompilation of
```
8900470:	addiu      $sp, $sp, -8
8900474:	sw         $ra, 4($sp)
8900478:	jal        0x0890C484
890047c:	nop
8900480:	lw         $ra, 4($sp)
8900484:	lui        $v1, 0x0891
8900488:	sw         $v0, 11904($v1)
890048c:	jr         $ra
8900490:	addiu      $sp, $sp, 8
```
gave me
```c++
int32_t startTest(void** a0, void** a1, void** a2) {
    int32_t v0_4;

    v0_4 = sceKernelGetSystemTimeLow();
    startSystemTime = v0_4;
    return 0x8910000;
}
```
I would expect something like:
```c++
int32_t startTest() {
    int32_t v0_4;

    v0_4 = sceKernelGetSystemTimeLow();
    startSystemTime = v0_4;
    return v0_4;
}
```

**Comment by nihilus** [comment] 2015-09-19 16:11
```
8900484:    lui        $v1, 0x0891
8900488:    sw         $v0, 11904($v1)
```
lui will do v1 = (0x0891 << 16);
then it goes wrong at 'sw' ending up with
v0 = v1;

**Comment by yegord** [comment] 2015-09-19 20:31
It looks like the decompiler thinks that the return value is in $v1. You currently cannot say that the return value can be in $v1 only if it is in $v0 too. Probably, I should fix this eventually.

**Comment by hlide** [comment] 2015-09-20 00:28
yes, return value is *v0* or pair *v1:v0* but noy *v1* alone. For this function, it should be only *v0*.

**Comment by yegord** [comment] 2015-10-05 22:46
Duplicate of https://github.com/yegord/snowman/issues/54

**Closed by yegord** 2015-10-05 22:46 UTC
Labels: enhancement
